from pydantic import BaseModel, Field

class ComplaintRequest(BaseModel):
    text: str = Field(..., description="The complaint text to analyze.", json_schema_extra={"example": "I have been waiting for my KYC update for 20 days! This is absolutely unacceptable!"})

class ComplaintResponse(BaseModel):
    sentiment: str = Field(..., description="The detected sentiment (e.g., POSITIVE, NEGATIVE, NEUTRAL).", json_schema_extra={"example": "NEGATIVE"})
    score: float = Field(..., description="The confidence score of the sentiment analysis.", json_schema_extra={"example": 0.98})
    priority: str = Field(..., description="The assigned priority level based on intent/sentiment.", json_schema_extra={"example": "HIGH"})
    intent: str = Field(..., description="The classified intent of the text.", json_schema_extra={"example": "COMPLAINT"})
    fraud_alert: bool = Field(False, description="Flag indicating potential fraudulent intent.", json_schema_extra={"example": False})

class OCRVerificationResponse(BaseModel):
    account_found: bool = Field(..., description="True if the account number was verified.", json_schema_extra={"example": True})
    extracted_text: list[str] = Field(..., description="List of text blocks extracted by OCR.", json_schema_extra={"example": ["HDFC BANK", "ACCOUNT: 123456789"]})
    message: str = Field(..., description="Details regarding the OCR verification.", json_schema_extra={"example": "Account number '123456789' successfully verified."})

class KYCVerificationResponse(BaseModel):
    match_found: bool = Field(..., description="True if the name and dob were verified in the document.", json_schema_extra={"example": True})
    extracted_text: list[str] = Field(..., description="List of text blocks extracted by OCR.", json_schema_extra={"example": ["JOHN DOE", "DOB: 1990-01-01"]})
    message: str = Field(..., description="Details regarding the KYC verification.", json_schema_extra={"example": "Name and DOB successfully verified."})

class ChatRequest(BaseModel):
    question: str = Field(..., description="The user's query.", json_schema_extra={"example": "How long does KYC updation take?"})
    history: list[dict] = Field([], description="Chat history array containing user and bot messages.", json_schema_extra={"example": [{"type": "user", "text": "Hi"}, {"type": "bot", "text": "Welcome to Finora Assist."}]})
    format: str = Field(None, description="Optional formatting constraint.", json_schema_extra={"example": "json"})

class ChatResponse(BaseModel):
    query: str = Field(..., description="The original query.", json_schema_extra={"example": "How long does KYC updation take?"})
    response: str = Field(..., description="The response generated by the AI.", json_schema_extra={"example": "Modification of KYC details will reflect within 2 working days."})
    retrieved_data_source: list[str] = Field(..., description="Sources used to answer the query.", json_schema_extra={"example": ["FAQ: How long does a KYC Updation take (SLA)?"]})
    sentiment: str = Field(..., description="The sentiment of the user's query.", json_schema_extra={"example": "NEUTRAL"})
    fraud_alert: bool = Field(False, description="Flag for fraud detection in chat.", json_schema_extra={"example": False})

class SummarizeRequest(BaseModel):
    ticket_data: dict = Field(..., description="Ticket data to summarize.", json_schema_extra={"example": {"title": "Update Address", "description": "Please update my address to Mumbai."}})

class SummarizeResponse(BaseModel):
    summary: list[str] = Field(..., description="Bullet points summarizing the ticket.", json_schema_extra={"example": ["User requests address update", "New address is in Mumbai"]})
